[package]
name = "{{project-name}}"
version = "0.1.0"
authors = ["{{authors}}"]
edition = "2018"

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
creator = "0.3.5"
bevy = "0.4.0"

[package.metadata.android]
build_targets = ["aarch64-linux-android"]
assets = "assets"
res = "res/android"

[package.metadata.android.manifest]
apk_label = "{{project-name}}"
fullscreen = true
icon = "@mipmap/ic_launcher"
target_sdk_version = 30
min_sdk_version = 16

[package.metadata.apple]
build_targets = ["aarch64-apple-ios", "x86_64-apple-ios"]
assets = "assets"
res = "res/apple"

[package.metadata.apple.info-plist]
bundle_name = "{{project-name}}"
bundle_identifier = "com.example.{{project-name}}"
bundle_executable = "{{project-name}}"
bundle_development_region = "en"
bundle_version = "1"
bundle_info_dictionary_version = "1.0"
bundle_short_version_string = "1.0"
bundle_package_type = "APPL"
launch_storyboard_name = "launch_storyboard_name"
requires_full_screen = false
supported_interface_orientations = ["portrait"]
