[package]
name = "{{project-name}}"
version = "0.1.0"
authors = ["{{authors}}"]
edition = "2018"

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
creator = { git = "https://github.com/creator-rs/creator", branch = "bevy-fix" }
bevy = { git = "https://github.com/creator-rs/bevy.git", branch = "bevy-0.4" }

[package.metadata]
app_name = "{{project-name}}"
icon = "ic_launcher"
target_sdk_version = 30

android_assets = "assets"
android_res = "res/android"

apple_assets = "assets"
apple_res = "res/apple"
