[package]
name = "{{project-name}}"
version = "0.1.0"
authors = ["{{authors}}"]
edition = "2018"

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
creator = "0.4.1"

[package.metadata]
icon = "ic_launcher"
android_res = "res/android"
apple_res = "res/apple"