[package]
name = "{{project-name}}"
version = "0.1.0"
authors = ["{{authors}}"]
edition = "2018"

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
creator = "0.3.9"
bevy = { git = "https://github.com/TheRawMeatball/bevy", branch = "android-support" }

[package.metadata]
apk_label = "{{project-name}}"
icon = "ic_launcher"
target_sdk_version = 30

android_assets = "assets"
android_res = "res/android"

apple_assets = "assets"
apple_res = "res/apple"
